import { DataTypes } from "sequelize"

const jobModel=(sequelize)=>{
    return sequelize.define("Job",
        {
            job_id:{
                type:DataTypes.INTEGER,
                primaryKey:true,
                autoIncrement:true
            },
            // JOB BASIC INFORMATION
            title:{ 
                type:DataTypes.STRING(255),
                allowNull:false
            },
            job_description:{
                type:DataTypes.TEXT,
                allowNull:false
            },
            requirements:{
                type:DataTypes.TEXT,
                allowNull:false
            },
            skills:{
                type:DataTypes.TEXT,
                allowNull:false
            },
            category_id:{
                type:DataTypes.INTEGER,
                allowNull:false
            },
            recruiter_id:{
                type:DataTypes.INTEGER,
                allowNull:false
            },
            location:{
                type:DataTypes.STRING(255),
                allowNull:false
            },
            work_mode:{
                type:DataTypes.ENUM(
                    "ONSITE",
                    "REMOTE",
                    "HYBRID"
                ),
                allowNull:false
            },
            employment_type:{
                type:DataTypes.ENUM(
                    "FULL_TIME",
                    "PART_TIME",
                    "CONTRACT",
                    "INTERNSHIP"
                ),
                allowNull:false
            },
            experience_min:{
                type:DataTypes.INTEGER,
                allowNull:false,
                defaultValue:0
            },
            experience_max:{
                type:DataTypes.INTEGER,
                allowNull:false,
            },
            salary_min:{
                type:DataTypes.INTEGER,
                allowNull:false,
                defaultValue:0
            },
            salary_max:{
                type:DataTypes.INTEGER,
                allowNull:false,
            },
            salary_currency:{
                type:DataTypes.STRING(10),
                allowNull:false,
                defaultValue:"INR"
            },
            vacancies:{
                type:DataTypes.INTEGER,
                allowNull:false,
                defaultValue:1
            },
            posted_on:{
                type:DataTypes.DATE,
                defaultValue:DataTypes.NOW,
                allowNull:false
            },
            application_deadline:{
                type:DataTypes.DATEONLY,
                allowNull:false
            },
            status:{
                type:DataTypes.ENUM(
                    "DRAFT",
                    "ACTIVE",
                    "CLOSED",
                    "EXPIRED"
                ),
                defaultValue:"DRAFT",
                allowNull:false
            }

        }
    )
}
export default jobModel